import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="container flex items-center justify-center h-screen mx-auto">{children}</body>
    </html>
  )
}
